services:
  app:
    build:
      context: .
      target: production
    image: gox:prod
    container_name: gox_prod
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
      - .env.prod
    ports:
      - "8080:8080" # host:container ; on-container port is defined in .env files (SERVER_PORT)
    command: [ "/app/app" ]

  db:
    image: postgres:15
    container_name: gox_prod_db
    restart: unless-stopped
    volumes:
      - ./_data-prod/postgres_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432" # host:container ; on-container port is defined in .env files (POSTGRES_PORT)
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "gox" ]
      interval: 10s
      retries: 5
